version: "3"

networks:
  inception:
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/migarcia/data/db
      o: bind

  wp:
    driver: local
    driver_opts:
      type: none
      device: /home/migarcia/data/wp
      o: bind     

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: requirements/mariadb/
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql/
    networks:
      - inception
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    build: requirements/wordpress
    env_file: .env
    ports:
      - "9000:9000"
    volumes:
      - wp:/var/www/html/
    networks:
      - inception
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    build: requirements/nginx
    env_file: .env
    ports:
      - "443:8443"
    volumes:
      - wp:/var/www/html/
      - ./log:/var/log/nginx/
    networks:
      - inception
    restart: always
