version: "3"

networks:
  inception:
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/migarcia/data/db
      o: bind

  wp:
    driver: local
    driver_opts:
      type: none
      device: /home/migarcia/data/wp
      o: bind     

  ssl:
    driver: local
    driver_opts:
      type: none
      device: /home/migarcia/data/ssl
      o: bind

services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql/
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: requirements/wordpress
    env_file: .env
    ports:
      - "9000:9000"
    volumes:
      - wp:/var/www/html/
    networks:
      - inception
    restart: always

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: requirements/nginx
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html/
    networks:
      - inception
    restart: always

  ftp:
    container_name: ftp
    build: requirements/ftp
    env_file: .env
    ports:
      - "21:21"
      - "21100:21100"
    volumes:
      - wp:/var/www/html
    networks:
     - inception
    restart: always

  redis:
    container_name: redis
    build: requirements/redis
    ports:
      - "6379:6379"
    networks:
     - inception
    restart: always

  adminer:
    container_name: adminer
    build: requirements/adminer
    ports:
      - "8080:8080"
    networks:
     - inception
    restart: always

  apache:
    container_name: apache
    build: requirements/apache
    ports:
      - "8081:8081"
    networks:
      - inception
    restart: always

  haproxy:
    container_name: haproxy
    build: requirements/haproxy
    ports:
      - "80:80"
    networks:
     - inception
    restart: always
